name: Build and Test

on:
  release:
    types: [ created ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:
  build:
    name: Build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Test
        run: dotnet test --configuration Release --no-build --logger trx --results-directory ./test-results/

      - name: Package
        run: dotnet pack --no-build --configuration Release --output ./build-output/

      - name: Upload nuget package artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Nuget Packages
          path: ./build-output/

      - name: Publish
        run: dotnet nuget push "./build-output/*.nupkg" --source nuget.org --api-key ${{ secrets.NUGET_TOKEN }}
